### ISSUE TITLE
Database storage

### ISSUE THREAD

**Issue by HamishWHC** [DenialAdams/glicko2#7]
Looking to use this in a project. I don't really understand the maths, but it seems that I would need to store 2 separate values (value and deviation) in order to store someone's rating in a database. Is this correct? And to display this rating, I simply display the value field, and not the deviation?

**Comment by DenialAdams** [comment]
> Looking to use this in a project. I don't really understand the maths, but it seems that I would need to store 2 separate values (value and deviation) in order to store someone's rating in a database. Is this correct? And to display this rating, I simply display the value field, and not the deviation?

Hi, sorry I missed your message until now - I was traveling recently.

Yes, you absolutely have the right idea. I would advise that you store player ratings as Glicko2 ratings, which is actually three components: Rating, Deviation and Volatility

And for display, I recommend using as a Glicko (1) rating which is just Rating and Deviation (on a different scale.) Some applications just display the rating to the user, but you could also choose to display the rating with a confidence interval based on the deviation. It's up to you.

Hope that helps, and feel free to let me know where I could make the docs more clear
